### ISSUE TITLE
Add a way to convert zap logger into implementation of go-kit's Logger

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/sallust#15]
Some libraries are being used by older services and newer services that require a go-kit [`Logger`](https://pkg.go.dev/github.com/unbxd/kit/log#Logger).  If we add logic to allow a service to switch over to sallust, without requiring a library requiring the old `Logger` interface to also be updated, we can prevent a snowball effect of sorts.

Once a library is updated to use the zap logger, services who have access to the `Logger` interface must update to use `zap` (and potentially require a need for more libraries to change over to the zap logger).  Otherwise, the service cannot update library versions until the zap changes are made.

**Comment by johnabass** [comment]
This feature should now be merged into the latest release.
